export const customerRows = [
  {
    id: 1,
    customer: "Olivia",
    img: "./assets/person/person1.jpg",
    email: "olivia@gmail.com",
    phoneNo: "0764534455",
    address: "Koswaththa, Battaramulla.",
  },
  {
    id: 2,
    customer: "Olivia",
    img: "./assets/person/person1.jpg",
    email: "olivia@gmail.com",
    phoneNo: "0764534455",
    address: "Koswaththa, Battaramulla.",
  },
  {
    id: 3,
    customer: "Olivia",
    img: "/assets/person/person1.jpg",
    email: "olivia@gmail.com",
    phoneNo: "0764534455",
    address: "Koswaththa, Battaramulla.",
  },
  {
    id: 5,
    customer: "Olivia",
    img: "/assets/person/person1.jpg",
    email: "olivia@gmail.com",
    phoneNo: "0764534455",
    address: "Koswaththa, Battaramulla.",
  },
  {
    id: 4,
    customer: "Olivia",
    img: "/assets/person/person1.jpg",
    email: "olivia@gmail.com",
    phoneNo: "0764534455",
    address: "Koswaththa, Battaramulla.",
  },
  {
    id: 6,
    customer: "Olivia",
    img: "/assets/person/person1.jpg",
    email: "olivia@gmail.com",
    phoneNo: "0764534455",
    address: "Koswaththa, Battaramulla.",
  },
  {
    id: 8,
    customer: "Olivia",
    img: "/assets/person/person1.jpg",
    email: "olivia@gmail.com",
    phoneNo: "0764534455",
    address: "Koswaththa, Battaramulla.",
  },
  {
    id: 7,
    customer: "Olivia",
    img: "/assets/person/person1.jpg",
    email: "olivia@gmail.com",
    phoneNo: "0764534455",
    address: "Koswaththa, Battaramulla.",
  },
];