export const productRows = [
    {
        id: 60,
        product: "Bag",
        img: "./assets/bag.jpg",
        description: "This bag is a....",
        supplier: "Olivia",
        unitPrice: "450",
        quantity: "15",
    },
    {
        id: 50,
        product: "Bag",
        img: "./assets/bag.jpg",
        description: "This bag is a....",
        supplier: "Olivia",
        unitPrice: "450",
        quantity: "15",
    },
    {
        id: 31,
        product: "Bag",
        img: "./assets/bag.jpg",
        description: "This bag is a....",
        supplier: "Olivia",
        unitPrice: "450",
        quantity: "15",
    },
    {
        id: 18,
        product: "Bag",
        img: "./assets/bag.jpg",
        description: "This bag is a....",
        supplier: "Olivia",
        unitPrice: "450",
        quantity: "15",
    },
    {
        id: 19,
        product: "Bag",
        img: "./assets/bag.jpg",
        description: "This bag is a....",
        supplier: "Olivia",
        unitPrice: "450",
        quantity: "15",
    },
    {
        id: 71,
        product: "Bag",
        img: "./assets/bag.jpg",
        description: "This bag is a....",
        supplier: "Olivia",
        unitPrice: "450",
        quantity: "15",
    },
    {
        id: 41,
        product: "Bag",
        img: "./assets/bag.jpg",
        description: "This bag is a....",
        supplier: "Olivia",
        unitPrice: "450",
        quantity: "15",
    },
    {
        id: 51,
        product: "Bag",
        img: "./assets/bag.jpg",
        description: "This bag is a....",
        supplier: "Olivia",
        unitPrice: "450",
        quantity: "15",
    },
]