export const orderRows = [
    {
        id: 1000,
        customer: "Olivia",
        shippingAddress: "Koswaththa, Battaramulla.",
        totalPrice: "1050",
        noOfItems: "5",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 1001,
        customer: "Olivia",
        shippingAddress: "Koswaththa, Battaramulla.",
        totalPrice: "1050",
        noOfItems: "5",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 1002,
        customer: "Olivia",
        shippingAddress: "Koswaththa, Battaramulla.",
        totalPrice: "1050",
        noOfItems: "5",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 1003,
        customer: "Olivia",
        shippingAddress: "Koswaththa, Battaramulla.",
        totalPrice: "1050",
        noOfItems: "5",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 1004,
        customer: "Olivia",
        shippingAddress: "Koswaththa, Battaramulla.",
        totalPrice: "1050",
        noOfItems: "5",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 1005,
        customer: "Olivia",
        shippingAddress: "Koswaththa, Battaramulla.",
        totalPrice: "1050",
        noOfItems: "5",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 1006,
        customer: "Olivia",
        shippingAddress: "Koswaththa, Battaramulla.",
        totalPrice: "1050",
        noOfItems: "5",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 1007,
        customer: "Olivia",
        shippingAddress: "Koswaththa, Battaramulla.",
        totalPrice: "1050",
        noOfItems: "5",
        date: "24 Oct 2024",
        time: "14:43",
    },
]