export const reviewRows = [
    {
        id: 25,
        customer: "Olivia",
        rating: "4.5",
        comment: "Great Product",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 11,
        customer: "Olivia",
        rating: "4.5",
        comment: "Great Product",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 31,
        customer: "Olivia",
        rating: "4.5",
        comment: "Great Product",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 51,
        customer: "Olivia",
        rating: "4.5",
        comment: "Great Product",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 41,
        customer: "Olivia",
        rating: "4.5",
        comment: "Great Product",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 17,
        customer: "Olivia",
        rating: "4.5",
        comment: "Great Product",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 18,
        customer: "Olivia",
        rating: "4.5",
        comment: "Great Product",
        date: "24 Oct 2024",
        time: "14:43",
    },
    {
        id: 10,
        customer: "Olivia",
        rating: "4.5",
        comment: "Great Product",
        date: "24 Oct 2024",
        time: "14:43",
    },
];