export const supplierRows = [
    {
        id: 92,
        supplier: "Olivia",
        img: "./assets/person/person1.jpg",
        email: "olivia@gmail.com",
        phoneNo: "0764534455",
        address: "Koswaththa, Battaramulla.",
    },
    {
        id: 93,
        supplier: "Olivia",
        img: "./assets/person/person1.jpg",
        email: "olivia@gmail.com",
        phoneNo: "0764534455",
        address: "Koswaththa, Battaramulla.",
    },
    {
        id: 94,
        supplier: "Olivia",
        img: "./assets/person/person1.jpg",
        email: "olivia@gmail.com",
        phoneNo: "0764534455",
        address: "Koswaththa, Battaramulla.",
    },
    {
        id: 95,
        supplier: "Olivia",
        img: "./assets/person/person1.jpg",
        email: "olivia@gmail.com",
        phoneNo: "0764534455",
        address: "Koswaththa, Battaramulla.",
    },
    {
        id: 96,
        supplier: "Olivia",
        img: "./assets/person/person1.jpg",
        email: "olivia@gmail.com",
        phoneNo: "0764534455",
        address: "Koswaththa, Battaramulla.",
    },
    {
        id: 97,
        supplier: "Olivia",
        img: "./assets/person/person1.jpg",
        email: "olivia@gmail.com",
        phoneNo: "0764534455",
        address: "Koswaththa, Battaramulla.",
    },
    {
        id: 98,
        supplier: "Olivia",
        img: "./assets/person/person1.jpg",
        email: "olivia@gmail.com",
        phoneNo: "0764534455",
        address: "Koswaththa, Battaramulla.",
    },
    {
        id: 99,
        supplier: "Olivia",
        img: "./assets/person/person1.jpg",
        email: "olivia@gmail.com",
        phoneNo: "0764534455",
        address: "Koswaththa, Battaramulla.",
    },
];